### ISSUE TITLE
403 forbidden when accessing scan.nextcloud.com

### ISSUE THREAD

**Issue by sumnerboy12** [janvonde/check_nextcloud#2]
This might be a local issue but I am no longer able to access the scan.nextclound.com API. Are you having any issues?

```
PHP Warning:  file_get_contents(https://scan.nextcloud.com/api/queue): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
 in /etc/icinga2/scripts/check_nextcloud.php on line 56
```

**Comment by janvonde** [comment]
Hm ... 

@lukasreschke, did you change anything at the API on your side with query limits? something that I could adopt to this plugin?

**Comment by sumnerboy12** [comment]
I don't think it is the API limiting, since I disabled the check for a few days and it still won't work. I presume you are seeing no issues from your end @janvonde?

**Comment by sumnerboy12** [comment]
this came right for a few months but is happening again now - anyone having issues?

**Comment by MarcusCaepio** [comment]
I can confirm this. Having the same issue right now

**Comment by sumnerboy12** [comment]
Stale, closing
